name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Install lcov (for genhtml)
        run: brew install lcov

      - name: Generate HTML coverage report
        run: genhtml coverage/lcov.info -o coverage/report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage-report
          path: coverage/report
